const imageModules = import.meta.glob("./mtc-members-photos/*.{jpg,png,webp}", {
  eager: true,
});

const teamImages = Object.entries(imageModules).reduce(
  (acc, [path, module]) => {
    const key = path.split("/").pop().replace(/\..+$/, "");
    acc[key] = module.default;
    return acc;
  },
  {}
);

const darkGradient = "linear-gradient(135deg,#a78bfa,#7c3aed,#4c1d95)";
const borderColor = "ffffff";

const coreMembers = [
  {
    image: teamImages["vennela"],
    title: "Vennela Vallabhaneni",
    subtitle: "Chair",
    handle: "@purpleone",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/venn.by",
    linkedIn: "https://linkedin.com/in/venn-v",
    github: "https://github.com/vennby",
  },
  {
    image: teamImages["siddharth"],
    title: "Siddharath Malavalli",
    subtitle: "Co-Chair",
    handle: "@purpletwo",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/siddharath_nagesh",
    linkedIn: "https://linkedin.com/in/siddharath-malavalli-nagesh-270b571ba",
    github: "https://github.com/Siddharath-Malavalli-Nagesh",
  },
  {
    image: teamImages["Ameiya"],
    title: "Ameiya Wankhede",
    subtitle: "Vice Chair",
    handle: "@purpletwo",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/ameiya.w",
    linkedIn: "https://linkedin.com/in/ameiya-wankhede",
    github: "https://github.com/aw2106",
  },
  {
    image: teamImages["Sri Hari Sai"],
    title: "Sri Hari Sai",
    subtitle: "General Secretary",
    handle: "@purpletwo",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/ft.hyper",
    linkedIn: "https://linkedin.com/in/sri-hari-sai-subramanian-737279322",
    github: "https://github.com/HyperPlexG",
  },
  {
    image: teamImages["Ankita"],
    title: "Ankita Menon",
    subtitle: "Ex-Officio",
    handle: "@purpletwo",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/ankita_menon_04",
    linkedIn: "https://linkedin.com/in/k-ankita-menon-4513b8232",
    github: "https://github.com/ankita-17-09",
  },
  {
    image: teamImages["Chhavi"],
    title: "Chhavi",
    subtitle: "Treasurer",
    handle: "@purpletwo",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/chhavithegreat",
    linkedIn: "https://linkedin.com/in/fnu-chhavi-094b6b286",
    github: "https://github.com/chhaavii",
  },
];

const technicalTeam = [
  {
    image: teamImages["Stellin"],
    title: "Stellin John",
    subtitle: "Tech Head",
    handle: "@stellinjohn",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/stellin_15",
    linkedIn: "https://linkedin.com/in/stellin-john-george-1bb757163",
    github: "https://github.com/Stellin-15",
  },
  {
    image: teamImages["Akshat"],
    title: "Akshat Singh",
    subtitle: "Tech Manager",
    handle: "@akshatsingh",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/Akshatlovesyou",
    linkedIn: "https://linkedin.com/in/akshatsingh-ind",
    github: "https://github.com/Akshatcodesyou",
  },
  {
    image: teamImages["Astha"],
    title: "Astha Adhikary",
    subtitle: "Tech Executive",
    handle: "@asthaadhikary",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_.astha.ad_",
    linkedIn: "https://linkedin.com/in/astha-adhikary-420713279",
    github: "https://github.com/astro-prog",
  },
  {
    image: teamImages["Nishal"],
    title: "Nishal Ahmed",
    subtitle: "Tech Executive",
    handle: "@nishalahmed",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/nishalahmxd",
    linkedIn: "https://linkedin.com/in/nishalahmed",
    github: "https://github.com/nishalahmedpk",
  },
  {
    image: teamImages["Raghubir"],
    title: "Raghubir Prasad",
    subtitle: "Tech Executive",
    handle: "@raghubirprasad",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/raghubir_0512",
    linkedIn: "https://linkedin.com/in/raghubir-prasad",
    github: "https://github.com/raghubirPrasad",
  },
  {
    image: teamImages["Sachin"],
    title: "Sachin Putlur",
    subtitle: "Tech Executive",
    handle: "@sachinputlur",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/sachin.premkumar",
    linkedIn: "https://linkedin.com/in/sachin-premkumar-74b66b30a",
    github: "https://github.com/SachinBits",
  },
  {
    image: teamImages["Tarakeshwar"],
    title: "Tarakeshwar K",
    subtitle: "Tech Executive",
    handle: "@tarakeshwark",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_tarakexwar_",
    linkedIn: "https://linkedin.com/in/ktarakeshwar",
    github: "https://github.com/Tarak101",
  },
  {
    image: teamImages["Neil"],
    title: "Neil Laturkar",
    subtitle: "Tech Executive",
    handle: "@neillaturkar",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/neillaturkar",
    linkedIn: "https://linkedin.com/in/neillaturkar",
    github: "https://github.com/orangebead",
  },
];

const devOpsTeam = [
  {
    image: teamImages["Adithya"],
    title: "Adithya Nandakumar",
    subtitle: "DevOps Manager",
    handle: "@adithyanandakumar",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/XantimaX_isMe",
    linkedIn: "https://linkedin.com/in/adithya-nandakumar-8b8061286",
    github: "https://github.com/XantimaX",
  },
  {
    image: teamImages["Sreenikethan"],
    title: "Sreenikethan Iyer",
    subtitle: "DevOps Manager",
    handle: "@sreenikethaniyer",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/sreenikethan.i",
    linkedIn: "https://linkedin.com/in/sreenikethan-i",
    github: "https://github.com/SreenikethanI",
  },
  {
    image: teamImages["Shanmukha"],
    title: "Shanmukha Srinanda",
    subtitle: "DevOps Manager",
    handle: "@shanmukhasrinanda",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/shanmu.kha",
    linkedIn: "https://linkedin.com/in/shanmukha-rapeti-724212254",
    github: "https://github.com/eatingmangoes",
  },
];

const eventsTeam = [
  {
    image: teamImages["Shahna"],
    title: "Shahna Shajahan",
    subtitle: "Events Manager",
    handle: "@shahnashajahan",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/shainaa04",
    linkedIn: "https://linkedin.com/in/shahna-shajahan-208821307",
    github: "https://github.com/ShahnaShaj",
  },
  {
    image: teamImages["Jahnavi"],
    title: "Jahnavi Angiras",
    subtitle: "Events Executive",
    handle: "@jahnaviangiras",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/jahnavi_angiras",
    linkedIn: "https://linkedin.com/in/jahnavi-angiras-1755a0300",
    github: "https://github.com/Janny18",
  },
  {
    image: teamImages["Manogna"],
    title: "Manogna Raju",
    subtitle: "Events Executive",
    handle: "@manognaraju",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/manogna0_0",
    linkedIn: "https://linkedin.com/in/manognaraju",
    github: "https://github.com/Manognaaaaaa",
  },
  {
    image: teamImages["Nirenjhena"],
    title: "Nirenjhena Venkatesan",
    subtitle: "Events Executive",
    handle: "@nirenjhenavenkatesan",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/nir__247",
    linkedIn: "https://linkedin.com/in/nirenjhena-venkatesan",
    github: "https://github.com/nirenjena",
  },
  {
    image: teamImages["Shaurya"],
    title: "Shaurya Srivastava",
    subtitle: "Events Executive",
    handle: "@shauryasrivastava",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/simply.shaurya",
    linkedIn: "https://linkedin.com/in/shauryasrivastava05",
    github: "https://github.com/pingu2024",
  },
];

const mediaOperationsTeam = [
  {
    image: teamImages["Sathvik"],
    title: "Sathvik Sreeram",
    subtitle: "Media Operations Head",
    handle: "@sathvik",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/sathvikboseman",
    linkedIn: "https://linkedin.com/in/sathvik-sreeram-06b350280",
    github: "https://github.com/sathvikboseman",
  },
  {
    image: teamImages["Saad"],
    title: "Saad Shafath",
    subtitle: "Media Operations Executive",
    handle: "@saad",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "",
    linkedIn: "https://linkedin.com/in/saad-shafath-rehman-3928a6376",
    github: "https://github.com/Saerzaer27",
  },
  {
    image: teamImages["Smrithi"],
    title: "Smrithi Ganesh",
    subtitle: "Media Operations Executive",
    handle: "@smrithi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/smithsterrrr____",
    linkedIn: "https://linkedin.com/in/smrithi-ganesh-283900309",
    github: "",
  },
];

const marketingTeam = [
  {
    image: teamImages["Khyati"],
    title: "Khyati Jetly",
    subtitle: "Marketing Head",
    handle: "@khyati",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_kxyati_",
    linkedIn: "https://linkedin.com/in/khyati-jetly-085792306",
    github: "https://github.com/khyati2107",
  },
  {
    image: teamImages["Srinjita"],
    title: "Srinjita Roy",
    subtitle: "Marketing Head",
    handle: "@srinjita",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/srinxie",
    linkedIn: "https://linkedin.com/in/srinjita-roy-chowdhury-99707531a",
    github: "https://github.com/Srinjita-RC",
  },
  {
    image: teamImages["Aminta"],
    title: "Aminta Thomas",
    subtitle: "Marketing Manager",
    handle: "@aminta",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/amintaa_bt",
    linkedIn: "https://linkedin.com/in/aminta-binu-thomas-435731331",
    github: "https://github.com/aminta-bt",
  },
  {
    image: teamImages["Prerana"],
    title: "Prerana Srikrishnan",
    subtitle: "Marketing Executive",
    handle: "@prerana",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_itz_me_prerana__",
    linkedIn: "https://linkedin.com/in/prerana-cs-0934b5366",
    github: "https://github.com/preranaaa0711",
  },
  {
    image: teamImages["Tanisha"],
    title: "Tanisha Handa",
    subtitle: "Marketing Executive",
    handle: "@tanisha",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/txnishx24",
    linkedIn: "",
    github: "",
  },
];

const creativeTeam = [
  {
    image: teamImages["Diya"],
    title: "Diya Vinu",
    subtitle: "Creative Head",
    handle: "@diya",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/dya.vnu",
    linkedIn: "https://linkedin.com/in/diya-vinu-058b7732a",
    github: "https://github.com/non-stickpanko",
  },
  {
    image: teamImages["Smredhi"],
    title: "Smredhi Shankar",
    subtitle: "Creative Manager",
    handle: "@smredhi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/smrredhi",
    linkedIn: "https://linkedin.com/in/smredhi-shankar-926210331",
    github: "https://github.com/smredhi",
  },
  {
    image: teamImages["Aravind"],
    title: "Aravind Renjith",
    subtitle: "Creative Executive",
    handle: "@smredhi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/arav.offcl",
    linkedIn: "https://linkedin.com/in/aravoffcl",
    github: "https://github.com/aravindrenjith",
  },
  {
    image: teamImages["Khyaati"],
    title: "Khyaati Runga",
    subtitle: "Creative Executive",
    handle: "@khyaati",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/khyaati_rungta",
    linkedIn: "https://linkedin.com/in/khyaati-rungta-4a2a6021b",
    github: "https://github.com/KhyaatiRungta",
  },
  {
    image: teamImages["Tarunikka"],
    title: "Tarunikka Suresh",
    subtitle: "Creative Advisor",
    handle: "@tarunikka",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/itztaruz",
    linkedIn: "https://linkedin.com/in/tarunikka-suresh-a39065278",
    github: "https://github.com/TarunikkaS",
  },
];

const outreachTeam = [
  {
    image: teamImages["Prasannah"],
    title: "Prasannah Raman",
    subtitle: "Outreach Head",
    handle: "@prasannah",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_prasannargh",
    linkedIn: "https://linkedin.com/in/prasannah-raman-0a7a6926b",
    github: "https://github.com/prastostart",
  },
  {
    image: teamImages["Hiteshi"],
    title: "Hiteshi Rajkumar",
    subtitle: "Outreach Executive",
    handle: "@hiteshi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/hitesheesh",
    linkedIn: "https://linkedin.com/in/hiteshi-rajkumar-312668313",
    github: "https://github.com/HiteshiRajkumar",
  },
  {
    image: teamImages["Saanvi"],
    title: "Saanvi Dutta",
    subtitle: "Outreach Executive",
    handle: "@saanvi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/Saanviidutta",
    linkedIn: "https://linkedin.com/in/saanvi-dutta-b21706317",
    github: "https://github.com/SAAN3108",
  },
  {
    image: teamImages["Vaibav"],
    title: "Vaibav Krishnan",
    subtitle: "Outreach Executive",
    handle: "@vaibav",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/vx.bav.yes3",
    linkedIn: "https://linkedin.com/in/vaibav-krishnan-1aa211321",
    github: "https://github.com/vaibav07",
  },
];

const communitySandboxTeam = [
  {
    image: teamImages["Vaibhav"],
    title: "Vaibhav Vinil Kumar",
    subtitle: "Community Relations Manager",
    handle: "@valbhav",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/vaibhav_vinil",
    linkedIn: "https://linkedin.com/in/vaibhav-vinil-87683a280",
    github: "https://github.com/Vaibhav-Vinil",
  },
  {
    image: teamImages["Crystal"],
    title: "Crystal Nazareth",
    subtitle: "Biotechnology Community Manager",
    handle: "@crystal",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/abigail.1007",
    linkedIn: "https://linkedin.com/in/crystal-nazareth-824a542b4",
    github: "https://github.com/Crystal-Nazareth",
  },
  {
    image: teamImages["Diya Freddy"],
    title: "Diya Freddy",
    subtitle: "Biotechnology Community Manager",
    handle: "@diya",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/diya.freddy",
    linkedIn: "https://linkedin.com/in/diya-freddy-1592012b4",
    github: "https://github.com/diyastudio1",
  },
  {
    image: teamImages["Shristi"],
    title: "Shristi Sudeep",
    subtitle: "Biotechnology Community Manager",
    handle: "@shristi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/moi_shristi",
    linkedIn: "https://linkedin.com/in/shristi-mukerjee-684803218",
    github: "https://github.com/Shristi7777",
  },
  {
    image: teamImages["Murtaza"],
    title: "Murtaza Rangwala",
    subtitle: "Electrical Community Manager",
    handle: "@murtaza",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/mrangwala16",
    linkedIn: "https://linkedin.com/in/murtaza-rangwala-85438b297",
    github: "https://github.com/Azatrum2005",
  },
  {
    image: teamImages["Reuben"],
    title: "Reuben Thomas",
    subtitle: "Electrical Community Manager",
    handle: "@reuben",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/reuben_thoo",
    linkedIn: "https://linkedin.com/in/reuben-thomas-thovelil-689893263",
    github: "https://github.com/reuben-tho",
  },
  {
    image: teamImages["Sree Gouri Menon"],
    title: "Sree Gouri Menon",
    subtitle: "Biotechnology Community Manager",
    handle: "@sreegouri",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/gouri_s_menon25",
    linkedIn: "https://linkedin.com/in/sree-gouri-menon-6a45512b4",
    github: "https://github.com/sree-gouri",
  },
];

const facultyInCharge = [
  {
    image: teamImages["drElakkiya"],
    title: "Dr. Elakkiya R.",
    subtitle: "Assistant Professor",
    handle: "@elakkiya",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "",
    linkedIn: "https://linkedin.com/in/elakkiya-r-581884b1",
    github: "",
  },
];

const councilSections = [
  { name: "Core Members", team: coreMembers },
  { name: "Technical Team", team: technicalTeam },
  { name: "DevOps Team", team: devOpsTeam },
  { name: "Events Team", team: eventsTeam },
  { name: "Media Operations Team", team: mediaOperationsTeam },
  { name: "Marketing Team", team: marketingTeam },
  { name: "Creative Team", team: creativeTeam },
  { name: "Outreach Team", team: outreachTeam },
  { name: "Community Sandbox Team", team: communitySandboxTeam },
  { name: "Faculty In-Charge", team: facultyInCharge },
];

export {
  councilSections,
  coreMembers,
  technicalTeam,
  devOpsTeam,
  eventsTeam,
  mediaOperationsTeam,
  marketingTeam,
  creativeTeam,
  outreachTeam,
  communitySandboxTeam,
  facultyInCharge,
};
