const imageModules = import.meta.glob("./mtc-members-photos/*.{jpg,png,webp}", {
  eager: true,
});

const teamImages = Object.entries(imageModules).reduce(
  (acc, [path, module]) => {
    const key = path.split("/").pop().replace(/\..+$/, "");
    acc[key] = module.default;
    return acc;
  },
  {}
);

const darkGradient = "linear-gradient(135deg,#a78bfa,#7c3aed,#4c1d95)";
const borderColor = "ffffff";

// NOTE: photos, Instagram, LinkedIn, and GitHub links for this term's council
// are still being collected. `image` is left null (TeamCard falls back to an
// initials avatar) and social links are left empty until they're provided --
// swap `image: null` for `image: teamImages["Full Name"]` (matching a photo
// filename in ./mtc-members-photos/) once photos are added.

const coreMembers = [
  {
    image: teamImages["Ameiya Wankhede"],
    imagePosition: "center 0%",
    title: "Ameiya Wankhede",
    subtitle: "Chair",
    handle: "@ameiya",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/ameiya.w",
    linkedIn: "https://linkedin.com/in/ameiya-wankhede",
    github: "https://github.com/aw2106",
  },
  {
    image: teamImages["Sri Hari Sai"],
    title: "Sri Hari Sai",
    subtitle: "Co-Chair",
    handle: "@srihariasai",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/ft.hyper",
    linkedIn: "https://linkedin.com/in/sri-hari-sai-subramanian-737279322",
    github: "https://github.com/HyperPlexG",
  },
  {
    image: teamImages["Jahnavi Angiras"],
    title: "Jahnavi Angiras",
    subtitle: "Vice Chair",
    handle: "@jahnavi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/jahnavi_angiras",
    linkedIn: "https://linkedin.com/in/jahnavi-angiras-1755a0300",
    github: "https://github.com/Janny18",
  },
  {
    image: teamImages["Chhavi"],
    imagePosition: "center 0%",
    title: "Chhavi",
    subtitle: "General Secretary",
    handle: "@chhavi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/chhavithegreat",
    linkedIn: "https://linkedin.com/in/fnu-chhavi-094b6b286",
    github: "https://github.com/chhaavii",
  },
  {
    image: teamImages["Aminta Binu Thomas"],
    title: "Aminta Binu Thomas",
    subtitle: "Treasurer/Marketing Head",
    handle: "@aminta",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/amintaa_bt",
    linkedIn: "https://linkedin.com/in/aminta-b-435731331",
    github: "https://github.com/aminta-bt",
  },
  {
    image: teamImages["Shahna Shajahan"],
    title: "Shahna Shajahan",
    subtitle: "Executive Coordinator",
    handle: "@shahna",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/shainaa04",
    linkedIn: "https://linkedin.com/in/shahna-shajahan-208821307",
    github: "https://github.com/ShahnaShaj",
  },
];

const technicalTeam = [
  {
    image: teamImages["Sachin Premkumar"],
    imagePosition: "center 10%",
    title: "Sachin Premkumar",
    subtitle: "Technical Head",
    handle: "@sachin",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/sachin.premkumar",
    linkedIn: "https://linkedin.com/in/sachin-premkumar-74b66b30a",
    github: "https://github.com/SachinBits",
  },
  {
    image: teamImages["Neil Laturkar"],
    title: "Neil Laturkar",
    subtitle: "Technical Manager",
    handle: "@neil",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/neillaturkar",
    linkedIn: "https://linkedin.com/in/neillaturkar",
    github: "https://github.com/orangebead",
  },
  {
    image: teamImages["Astha Adhikary"],
    title: "Astha Adhikary",
    subtitle: "Technical Manager",
    handle: "@astha",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_.astha.ad_",
    linkedIn: "https://linkedin.com/in/astha-adhikary-420713279",
    github: "https://github.com/astro-prog",
  },
  {
    image: teamImages["Mohammad Sayem"],
    title: "Mohammad Sayem",
    subtitle: "Technical Executive",
    handle: "@sayem",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_sayem95_",
    linkedIn: "https://linkedin.com/in/mohdsayem",
    github: "https://github.com/95maestro",
  },
  {
    image: teamImages["Sanjit Madan Kumar"],
    imagePosition: "center 25%",
    title: "Sanjit Madan Kumar",
    subtitle: "Technical Executive",
    handle: "@sanjit",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/fw.sanjit",
    linkedIn: "https://linkedin.com/in/sanjit-madan-kumar-494276323",
    github: "https://github.com/mrepiepie",
  },
  {
    image: teamImages["Deekshita Suresh"],
    imagePosition: "center 15%",
    title: "Deekshita Suresh",
    subtitle: "Technical Executive",
    handle: "@deekshita",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/deeki273",
    linkedIn: "https://linkedin.com/in/deekshita-suresh-180a22382",
    github: "https://github.com/deekshita247",
  },
  {
    image: teamImages["Aabid Anas"],
    title: "Aabid Anas",
    subtitle: "Technical Executive",
    handle: "@aabid",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/aabidanass_",
    linkedIn: "https://linkedin.com/in/aabidanas",
    github: "https://github.com/Aabidanas",
  },
];

const devOpsTeam = [
  {
    image: teamImages["Nishal Ahmed"],
    title: "Nishal Ahmed",
    subtitle: "DevOps Manager",
    handle: "@nishalahmed",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/nishalahmxd",
    linkedIn: "https://linkedin.com/in/nishalahmed",
    github: "https://github.com/nishalpk",
  },
  {
    image: teamImages["Raghubir K S Prasad"],
    title: "Raghubir K S Prasad",
    subtitle: "DevOps Manager",
    handle: "@raghubirprasad",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/raghubir_0512",
    linkedIn: "https://linkedin.com/in/raghubir-prasad",
    github: "https://github.com/raghubirPrasad",
  },
];

const eventsTeam = [
  {
    image: teamImages["Manogna Raju"],
    title: "Manogna Raju",
    subtitle: "Events Head",
    handle: "@manognaraju",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/manogna0_0",
    linkedIn: "https://linkedin.com/in/manognaraju",
    github: "https://github.com/Manognaaaaaa",
  },
  {
    image: teamImages["Rahul Bhaskar"],
    imagePosition: "center 20%",
    title: "Rahul Bhaskar",
    subtitle: "Events Executive",
    handle: "@rahulbhaskar",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/rahul_et_al._",
    linkedIn: "https://linkedin.com/in/rahul-bhaskar-643a31283",
    github: "https://github.com/Rhlbhskr",
  },
  {
    image: teamImages["Khushi Shetty"],
    title: "Khushi Shetty",
    subtitle: "Events Executive",
    handle: "@khushishetty",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/khushiiii.shetty",
    linkedIn: "https://linkedin.com/in/khushi-shetty88",
    github: "https://github.com/khushishetty8",
  },
  {
    image: teamImages["Surya Vijith"],
    imagePosition: "center 20%",
    title: "Surya Vijith",
    subtitle: "Events Executive",
    handle: "@suryavijith",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/surya.vijith",
    linkedIn: "https://linkedin.com/in/surya-vijith-176972347",
    github: "https://github.com/suryav2525",
  },
];

const marketingTeam = [
  {
    image: teamImages["Prerana Srikrishnan"],
    imagePosition: "center 20%",
    title: "Prerana Srikrishnan",
    subtitle: "Marketing Manager",
    handle: "@prerana",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_itz_me_prerana__",
    linkedIn: "https://linkedin.com/in/prerana-cs-0934b5366",
    github: "https://github.com/preranaaa0711",
  },
  {
    image: teamImages["Smrithi Ganesh"],
    imagePosition: "center 15%",
    title: "Smrithi Ganesh",
    subtitle: "Marketing Manager",
    handle: "@smrithi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/smithsterrrr____",
    linkedIn: "https://linkedin.com/in/smrithi-ganesh-283900309",
    github: "",
  },
  {
    image: teamImages["Michelle Moses"],
    title: "Michelle Moses",
    subtitle: "Marketing Executive",
    handle: "@michellemoses",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_mi_chelle.m_",
    linkedIn: "https://linkedin.com/in/michelle-moses-620b8b340",
    github: "https://github.com/MMichelle581",
  },
  {
    image: teamImages["Amna Aleem"],
    title: "Amna Aleem",
    subtitle: "Marketing Executive",
    handle: "@amnaaleem",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/amna.heheheh",
    linkedIn: "https://linkedin.com/in/amna-aleem-7a3463316",
    github: "https://github.com/amnaaaaa765",
  },
  {
    image: teamImages["Tanishka Mazumdar"],
    imagePosition: "center 20%",
    title: "Tanishka Mazumdar",
    subtitle: "Marketing Executive",
    handle: "@tanishka",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/__tanishkaaaaaa",
    linkedIn: "https://linkedin.com/in/tanishka-mazumdar",
    github: "",
  },
];

const creativeTeam = [
  {
    image: teamImages["Aravind Renjith"],
    imagePosition: "center 20%",
    title: "Aravind Renjith",
    subtitle: "Creative Head",
    handle: "@aravindrenjith",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/arav.offcl",
    linkedIn: "https://linkedin.com/in/aravoffcl",
    github: "https://github.com/aravindrenjith",
  },
  {
    image: teamImages["Smredhi Shankar"],
    imagePosition: "center 20%",
    title: "Smredhi Shankar",
    subtitle: "Creative Advisor",
    handle: "@smredhi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/smrredhi",
    linkedIn: "https://linkedin.com/in/smredhi-shankar-926210331",
    github: "https://github.com/smredhi",
  },
  {
    image: teamImages["Vainika Srikanth"],
    imagePosition: "center 15%",
    title: "Vainika Srikanth",
    subtitle: "Creative Executive",
    handle: "@vainika",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/y_nika_18",
    linkedIn: "https://linkedin.com/in/vainika-srikanth",
    github: "https://github.com/vainika2007118",
  },
  {
    image: teamImages["Saloni Nayak"],
    imagePosition: "center 10%",
    title: "Saloni Nayak",
    subtitle: "Creative Executive",
    handle: "@saloninayak",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/luv.saloni",
    linkedIn: "",
    github: "https://github.com/saloninayak2020-lang",
  },
];

const outreachTeam = [
  {
    image: teamImages["Shaurya Srivastava"],
    title: "Shaurya Srivastava",
    subtitle: "Outreach Head",
    handle: "@shauryasrivastava",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/simply.shaurya",
    linkedIn: "https://linkedin.com/in/shauryasrivastava05",
    github: "https://github.com/pingu2024",
  },
  {
    image: teamImages["Saanvi Dutta"],
    imagePosition: "center 15%",
    title: "Saanvi Dutta",
    subtitle: "Outreach Manager",
    handle: "@saanvi",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/Saanviidutta",
    linkedIn: "https://linkedin.com/in/saanvi-dutta-b21706317",
    github: "https://github.com/SAAN3108",
  },
  {
    image: teamImages["Vaibav Krishnan"],
    imagePosition: "center 30%",
    title: "Vaibav Krishnan",
    subtitle: "Outreach Manager",
    handle: "@vaibav",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/vx.bav.yes3",
    linkedIn: "https://linkedin.com/in/vaibav-krishnan-1aa211321",
    github: "https://github.com/vaibav07",
  },
  {
    image: teamImages["Prisha Gupta"],
    imagePosition: "center 20%",
    title: "Prisha Gupta",
    subtitle: "Outreach Executive",
    handle: "@prishagupta",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/prishafr",
    linkedIn: "https://linkedin.com/in/prishafr",
    github: "",
  },
  {
    image: teamImages["Parvathy Gopakumar"],
    title: "Parvathy Gopakumar",
    subtitle: "Outreach Executive",
    handle: "@parvathy",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "",
    linkedIn: "",
    github: "",
  },
  {
    image: teamImages["Arham Chetan Jain"],
    imagePosition: "center 0%",
    title: "Arham Chetan Jain",
    subtitle: "Outreach Executive",
    handle: "@arham",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/arham_jain14",
    linkedIn: "https://linkedin.com/in/arham-chetan-jain-b42304220",
    github: "https://github.com/ArhamChetanJain",
  },
];

const communitySandboxTeam = [
  {
    image: teamImages["Nirenjhena Venkatesan"],
    imagePosition: "center 15%",
    title: "Nirenjhena Venkatesan",
    subtitle: "Sandbox Head",
    handle: "@nirenjhena",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/nir__247",
    linkedIn: "https://linkedin.com/in/nirenjhena-venkatesan",
    github: "https://github.com/nirenjena",
  },
  {
    image: teamImages["Shreya Nambiar"],
    imagePosition: "center 30%",
    title: "Shreya Nambiar",
    subtitle: "Research Manager",
    handle: "@shreya",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/shreywv",
    linkedIn: "https://linkedin.com/in/shreyanambiar",
    github: "https://github.com/shreywv2007",
  },
  {
    image: teamImages["Doreen Parekh"],
    title: "Doreen Parekh",
    subtitle: "Research Executive",
    handle: "@doreen",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/dxreen_20",
    linkedIn: "https://linkedin.com/in/doreenparekh",
    github: "https://github.com/doreensys",
  },
  {
    image: teamImages["Shaun Gonsalves"],
    imagePosition: "center 30%",
    title: "Shaun Gonsalves",
    subtitle: "Research Executive",
    handle: "@shaun",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "https://instagram.com/_shaun11.7",
    linkedIn: "https://linkedin.com/in/shaun-gonsalves-516429331",
    github: "https://github.com/ShaunGves",
  },
];

const facultyInCharge = [
  {
    image: teamImages["drElakkiya"],
    title: "Dr. Elakkiya R.",
    subtitle: "Assistant Professor",
    handle: "@elakkiya",
    borderColor: borderColor,
    gradient: darkGradient,
    instagram: "",
    linkedIn: "https://linkedin.com/in/elakkiya-r-581884b1",
    github: "",
  },
];

const councilSections = [
  { name: "Core Members", team: coreMembers },
  { name: "Technical Team", team: technicalTeam },
  { name: "DevOps Team", team: devOpsTeam },
  { name: "Events Team", team: eventsTeam },
  { name: "Marketing Team", team: marketingTeam },
  { name: "Creative Team", team: creativeTeam },
  { name: "Outreach Team", team: outreachTeam },
  { name: "Community Sandbox Team", team: communitySandboxTeam },
  { name: "Faculty In-Charge", team: facultyInCharge },
];

export {
  councilSections,
  coreMembers,
  technicalTeam,
  devOpsTeam,
  eventsTeam,
  marketingTeam,
  creativeTeam,
  outreachTeam,
  communitySandboxTeam,
  facultyInCharge,
};
