-- ============================================================================
-- Fix: members created only via CSV import (event participation, never
-- registered through /join) had a referral_code generated by the
-- members_before_insert trigger but no way to ever see it -- the public
-- "check my points" lookup didn't return it, and only the /join confirmation
-- screen ever displayed a code. This makes the referral code visible to
-- every member via the same BITS ID lookup they'd already use to check
-- points, regardless of how they joined.
-- ============================================================================

create or replace function lookup_member_by_bits_id(p_bits_id text) returns jsonb
language plpgsql
security definer
stable
as $$
declare
  v_member_id uuid;
  v_name text;
  v_referral_code text;
  v_total int;
  v_rank int;
  v_history jsonb;
begin
  select id, name, referral_code into v_member_id, v_name, v_referral_code
  from members
  where bits_id = upper(trim(p_bits_id));

  if v_member_id is null then
    return jsonb_build_object('found', false);
  end if;

  select total_points, rank into v_total, v_rank
  from leaderboard
  where member_id = v_member_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'event_name', t.event_name,
        'achievement', t.achievement,
        'source', t.source,
        'points', t.points,
        'reason', t.reason,
        'created_at', t.created_at
      )
      order by t.created_at desc
    ),
    '[]'::jsonb
  )
  into v_history
  from point_transactions t
  where t.member_id = v_member_id
    and t.academic_year = current_academic_year();

  return jsonb_build_object(
    'found', true,
    'name', v_name,
    'referral_code', v_referral_code,
    'total_points', coalesce(v_total, 0),
    'rank', v_rank,
    'history', v_history
  );
end;
$$;

grant execute on function lookup_member_by_bits_id(text) to anon, authenticated;
